package utils

const (
	ERR_AUTHORIZATION = "405"
	ERR_BAD_REQUEST = "400"
	ERR_VALIDATE_DATA = "201"
	ERR_FILE_NOT_FOUND = "202"
	ERR_DELETE_FILE = "203"
	ERR_GLOBAL = "204"
	SUCCESS_CODE ="200"
	TYPE_EMAIL_INV_CANCEL = "EMAIL_INV_CANCEL"
	TYPE_EMAIL_NO_FP  = "EMAIL_INV_NO_FP"
	TYPE_EMAIL_INV_NOT_SEND = "EMAIL_INV_NOT_SEND"
	TYPE_EMAIL_NO_FILE_FP = "EMAIL_NO_FILE_FP"
	TYPE_EMAIL_FP_CANCEL = "EMAIL_FP_CANCEL"
	TYPE_EMAIL_FP_NOT_SEND = "EMAIL_FP_NOT_SEND"
    TYPE_DATE_RFC3339 = "2006-01-02"
    LIMIT_OF_UPLOAD_FPM = 1000
)


